version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "80:5000"  
    volumes:
      - ./server:/app  
    environment:
      - FLASK_APP=webapp.py  
      - FLASK_ENV=development  
  web:
    build: ./client/my-react-app
    ports:
      - "3000:3000"
    volumes:
      - .client/my-react-app /user/src/app
    depends_on:
      - flask_app

  